name: Deploy
run-name: ${{ github.actor }} is deploying the React app

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]

        steps:
        - run: echo "now building & testing the app"
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          working-directory: ./react-fe
          run: npm ci
        - name: Build React app
          working-directory: ./react-fe
          run: npm run build

    