name: Deploy
run-name: ${{ github.actor }} is deploying the React app

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Build-And-Test"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        working-directory: ./react-fe
        run: npm ci
      
      - name: Build React app
        working-directory: ./react-fe
        run: npm run build

  build-and-push-docker:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./react-fe
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-app-name:latest