name: Deploy
run-name: ${{ github.actor }} is deploying the React app

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-an-deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2
      
          - name: Use Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '18.x'
      
          - name: Install dependencies
            working-directory: ./react-fe
            run: npm ci
      
          - name: Build React app
            working-directory: ./react-fe
            run: npm run build


    